"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import os

from dotenv import load_dotenv


SETTINGS_DIR = Path(__file__).resolve().parent

BACKEND_DIR = SETTINGS_DIR.parent

PROJECT_ROOT = BACKEND_DIR.parent


load_dotenv(
    PROJECT_ROOT / ".env"
)


def env_bool(name, default=False):
    fallback = "True" if default else "False"
    return os.getenv(name, fallback).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default):
    raw_value = os.getenv(name, "")
    if not raw_value.strip():
        return list(default)
    return [value.strip() for value in raw_value.split(",") if value.strip()]


# ==========================================
# PATHS
# ==========================================

BASE_DIR = (
    Path(__file__)
    .resolve()
    .parent
    .parent
)


# ==========================================
# SECURITY
# ==========================================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "dev-only-secret-key"
)

DEBUG = env_bool("DJANGO_DEBUG", False)


ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    ["localhost", "127.0.0.1", "178.104.47.231"],
)


CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    ["http://178.104.47.231", "http://178.104.47.231:8080"],
)

HTTPS_ENABLED = env_bool("BAZKIT_HTTPS_ENABLED", False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = HTTPS_ENABLED
SESSION_COOKIE_SECURE = HTTPS_ENABLED
CSRF_COOKIE_SECURE = HTTPS_ENABLED
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_HSTS_SECONDS", "31536000")) if HTTPS_ENABLED else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = HTTPS_ENABLED and env_bool(
    "DJANGO_HSTS_INCLUDE_SUBDOMAINS",
    False,
)
SECURE_HSTS_PRELOAD = HTTPS_ENABLED and env_bool("DJANGO_HSTS_PRELOAD", False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"


# ==========================================
# APPLICATIONS
# ==========================================

INSTALLED_APPS = [

    "django.contrib.admin",

    "django.contrib.auth",

    "django.contrib.contenttypes",

    "django.contrib.sessions",

    "django.contrib.messages",

    "django.contrib.staticfiles",


    "corsheaders",

    "rest_framework",

    "channels",


    "users",

    "lists",

    "products",

    "recipes",

    "planner",

    "community",

    "monitoring",
]


AUTH_USER_MODEL = (
    "users.User"
)


# ==========================================
# MIDDLEWARE
# ==========================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.middleware.gzip.GZipMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "corsheaders.middleware.CorsMiddleware",
]


# ==========================================
# CORS
# ==========================================

CORS_ALLOWED_ORIGINS = env_list(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    ["http://178.104.47.231", "http://178.104.47.231:8080"],
)


# ==========================================
# URLS / TEMPLATES
# ==========================================

ROOT_URLCONF = (
    "config.urls"
)


TEMPLATES = [

    {

        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.debug",

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = (
    "config.wsgi.application"
)

ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL", "redis://localhost:6379/0")],
        },
    },
}


# ==========================================
# DATABASE
# ==========================================

DATABASES = {

    "default": {

        "ENGINE":
            "django.db.backends.postgresql",

        "NAME":
            os.getenv(
                "POSTGRES_DB"
            ),

        "USER":
            os.getenv(
                "POSTGRES_USER"
            ),

        "PASSWORD":
            os.getenv(
                "POSTGRES_PASSWORD"
            ),

        "HOST":
            os.getenv(
                "POSTGRES_HOST",
                "localhost"
            ),

        "PORT":
            os.getenv(
                "POSTGRES_PORT",
                "5432"
            ),

        "CONN_MAX_AGE":
            int(
                os.getenv(
                    "DB_CONN_MAX_AGE",
                    "60"
                )
            ),

        "CONN_HEALTH_CHECKS": True,
    }
}


# ==========================================
# PASSWORD VALIDATION
# ==========================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ==========================================
# INTERNATIONALIZATION
# ==========================================

LANGUAGE_CODE = (
    "en-us"
)

TIME_ZONE = (
    "UTC"
)

USE_I18N = True

USE_TZ = True


# ==========================================
# STATIC FILES
# ==========================================

STATIC_URL = (
    "static/"
)


DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ==========================================
# DJANGO REST FRAMEWORK
# ==========================================

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (

        "rest_framework_simplejwt.authentication.JWTAuthentication",

    ),

    "DEFAULT_THROTTLE_RATES": {
        "browser_errors": "20/minute",
    },

    "NUM_PROXIES": 1,
}

AUTH_THROTTLES_ENABLED = os.getenv(
    "AUTH_THROTTLES_ENABLED",
    "True",
).lower() in {"1", "true", "yes", "on"}


# ==========================================
# JWT
# ==========================================

SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME":
        timedelta(
            minutes=60
        ),

    "AUTH_HEADER_TYPES": (
        "Bearer",
    ),

    "CHECK_REVOKE_TOKEN": True,
}


# ==========================================
# OPENAI
# ==========================================

OPENAI_API_KEY = os.getenv(
    "OPENAI_API_KEY",
    ""
)


OPENAI_RECIPE_MODEL = os.getenv(
    "OPENAI_RECIPE_MODEL",
    "gpt-5-mini"
)

OPENAI_RECIPE_TIMEOUT_SECONDS = float(
    os.getenv("OPENAI_RECIPE_TIMEOUT_SECONDS", "90")
)

OPENAI_RECIPE_MAX_RETRIES = int(
    os.getenv("OPENAI_RECIPE_MAX_RETRIES", "0")
)

OPENAI_RECIPE_CATALOG_LIMIT = int(
    os.getenv("OPENAI_RECIPE_CATALOG_LIMIT", "300")
)

OPENAI_RECIPE_MAX_OUTPUT_TOKENS = int(
    os.getenv("OPENAI_RECIPE_MAX_OUTPUT_TOKENS", "3000")
)


# Während der Startphase erhalten alle Konten das Premium-Kontingent. Sobald
# das Bezahlmodell verfügbar ist, genügt PREMIUM_ENFORCEMENT_ENABLED=True; dann
# erhalten nur freigeschaltete Konten 50 und alle anderen 5 Generierungen.
PREMIUM_ENFORCEMENT_ENABLED = (
    os.getenv("PREMIUM_ENFORCEMENT_ENABLED", "False").lower()
    in {"1", "true", "yes", "on"}
)
AI_RECIPE_FREE_MONTHLY_LIMIT = int(
    os.getenv("AI_RECIPE_FREE_MONTHLY_LIMIT", "5")
)
AI_RECIPE_PREMIUM_MONTHLY_LIMIT = int(
    os.getenv("AI_RECIPE_PREMIUM_MONTHLY_LIMIT", "50")
)
LEGAL_TERMS_VERSION = os.getenv("LEGAL_TERMS_VERSION", "2026-10-01")


# ==========================================
# E-MAIL / KONTOBESTÄTIGUNG
# ==========================================

FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://localhost:4200" if DEBUG else "http://178.104.47.231:8080",
)

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in {
    "1", "true", "yes", "on",
}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in {
    "1", "true", "yes", "on",
}
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "bazkit <kontakt@ferchow-eugen.de>",
)
EMAIL_VERIFICATION_TIMEOUT_HOURS = int(
    os.getenv("EMAIL_VERIFICATION_TIMEOUT_HOURS", "24")
)
EMAIL_VERIFICATION_RESEND_SECONDS = int(
    os.getenv("EMAIL_VERIFICATION_RESEND_SECONDS", "60")
)
PASSWORD_RESET_TIMEOUT = int(os.getenv("PASSWORD_RESET_TIMEOUT", "7200"))
CONTACT_EMAIL = os.getenv("CONTACT_EMAIL", "kontakt@ferchow-eugen.de")


# ==========================================
# LOGGING
# ==========================================

ERROR_MONITORING_ENABLED = os.getenv(
    "ERROR_MONITORING_ENABLED",
    "False" if DEBUG else "True",
).lower() in {"1", "true", "yes", "on"}
ERROR_ALERT_EMAIL = os.getenv(
    "ERROR_ALERT_EMAIL",
    "kontakt@ferchow-eugen.de",
)
ERROR_ALERT_COOLDOWN_MINUTES = int(
    os.getenv("ERROR_ALERT_COOLDOWN_MINUTES", "30")
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
        "operational_issues": {
            "()": "monitoring.handlers.OperationalIssueHandler",
            "level": "ERROR",
        },
    },
    "root": {
        "handlers": ["console", "operational_issues"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console", "operational_issues"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# USDA FoodData Central ist ein optionaler Nährwert-Fallback. Ohne Key arbeitet
# die Rezeptsuche ausschließlich mit dem lokalen BLS und geprüften OFF-Daten.
USDA_FDC_API_KEY = os.getenv(
    "USDA_FDC_API_KEY",
    "",
)


# ==========================================
# CLOUDFLARE R2 / BILDER
# ==========================================

R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY", "")
R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME", "")
R2_ENDPOINT_URL = os.getenv("R2_ENDPOINT_URL", "")
R2_PRESIGNED_URL_TTL = int(os.getenv("R2_PRESIGNED_URL_TTL", "3600"))
RECIPE_IMAGE_MAX_BYTES = int(os.getenv("RECIPE_IMAGE_MAX_BYTES", str(10 * 1024 * 1024)))
