"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import os

from dotenv import load_dotenv


SETTINGS_DIR = Path(__file__).resolve().parent

BACKEND_DIR = SETTINGS_DIR.parent

PROJECT_ROOT = BACKEND_DIR.parent


load_dotenv(
    PROJECT_ROOT / ".env"
)


# ==========================================
# PATHS
# ==========================================

BASE_DIR = (
    Path(__file__)
    .resolve()
    .parent
    .parent
)


# ==========================================
# SECURITY
# ==========================================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "dev-only-secret-key"
)

DEBUG = (
    os.getenv(
        "DJANGO_DEBUG",
        "False"
    )
    ==
    "True"
)


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "178.104.47.231",
]


CSRF_TRUSTED_ORIGINS = [
    "http://178.104.47.231",
]


# ==========================================
# APPLICATIONS
# ==========================================

INSTALLED_APPS = [

    "django.contrib.admin",

    "django.contrib.auth",

    "django.contrib.contenttypes",

    "django.contrib.sessions",

    "django.contrib.messages",

    "django.contrib.staticfiles",


    "corsheaders",

    "rest_framework",


    "users",

    "lists",

    "products",

    "recipes",

    "planner",

    "community",
]


AUTH_USER_MODEL = (
    "users.User"
)


# ==========================================
# MIDDLEWARE
# ==========================================

MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.middleware.gzip.GZipMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "corsheaders.middleware.CorsMiddleware",
]


# ==========================================
# CORS
# ==========================================

CORS_ALLOWED_ORIGINS = [

    "http://178.104.47.231",

    "http://178.104.47.231:8080",
]


# ==========================================
# URLS / TEMPLATES
# ==========================================

ROOT_URLCONF = (
    "config.urls"
)


TEMPLATES = [

    {

        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.debug",

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = (
    "config.wsgi.application"
)


# ==========================================
# DATABASE
# ==========================================

DATABASES = {

    "default": {

        "ENGINE":
            "django.db.backends.postgresql",

        "NAME":
            os.getenv(
                "POSTGRES_DB"
            ),

        "USER":
            os.getenv(
                "POSTGRES_USER"
            ),

        "PASSWORD":
            os.getenv(
                "POSTGRES_PASSWORD"
            ),

        "HOST":
            os.getenv(
                "POSTGRES_HOST",
                "localhost"
            ),

        "PORT":
            os.getenv(
                "POSTGRES_PORT",
                "5432"
            ),

        "CONN_MAX_AGE":
            int(
                os.getenv(
                    "DB_CONN_MAX_AGE",
                    "60"
                )
            ),

        "CONN_HEALTH_CHECKS": True,
    }
}


# ==========================================
# PASSWORD VALIDATION
# ==========================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ==========================================
# INTERNATIONALIZATION
# ==========================================

LANGUAGE_CODE = (
    "en-us"
)

TIME_ZONE = (
    "UTC"
)

USE_I18N = True

USE_TZ = True


# ==========================================
# STATIC FILES
# ==========================================

STATIC_URL = (
    "static/"
)


DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ==========================================
# DJANGO REST FRAMEWORK
# ==========================================

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (

        "rest_framework_simplejwt.authentication.JWTAuthentication",

    ),
}


# ==========================================
# JWT
# ==========================================

SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME":
        timedelta(
            minutes=60
        ),

    "AUTH_HEADER_TYPES": (
        "Bearer",
    ),
}


# ==========================================
# OPENAI
# ==========================================

OPENAI_API_KEY = os.getenv(
    "OPENAI_API_KEY",
    ""
)


OPENAI_RECIPE_MODEL = os.getenv(
    "OPENAI_RECIPE_MODEL",
    "gpt-5-mini"
)


# Während der Startphase erhalten alle Konten das Premium-Kontingent. Sobald
# das Bezahlmodell verfügbar ist, genügt PREMIUM_ENFORCEMENT_ENABLED=True; dann
# erhalten nur freigeschaltete Konten 50 und alle anderen 5 Generierungen.
PREMIUM_ENFORCEMENT_ENABLED = (
    os.getenv("PREMIUM_ENFORCEMENT_ENABLED", "False").lower()
    in {"1", "true", "yes", "on"}
)
AI_RECIPE_FREE_MONTHLY_LIMIT = int(
    os.getenv("AI_RECIPE_FREE_MONTHLY_LIMIT", "5")
)
AI_RECIPE_PREMIUM_MONTHLY_LIMIT = int(
    os.getenv("AI_RECIPE_PREMIUM_MONTHLY_LIMIT", "50")
)
LEGAL_TERMS_VERSION = os.getenv("LEGAL_TERMS_VERSION", "2026-09-05")


# USDA FoodData Central ist ein optionaler Nährwert-Fallback. Ohne Key arbeitet
# die Rezeptsuche ausschließlich mit dem lokalen BLS und geprüften OFF-Daten.
USDA_FDC_API_KEY = os.getenv(
    "USDA_FDC_API_KEY",
    "",
)


# ==========================================
# CLOUDFLARE R2 / REZEPTBILDER
# ==========================================

R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY", "")
R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME", "")
R2_ENDPOINT_URL = os.getenv("R2_ENDPOINT_URL", "")
R2_PRESIGNED_URL_TTL = int(os.getenv("R2_PRESIGNED_URL_TTL", "3600"))
RECIPE_IMAGE_MAX_BYTES = int(os.getenv("RECIPE_IMAGE_MAX_BYTES", str(10 * 1024 * 1024)))
