# Generated by Django 6.1 on 2026-08-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_calories_per_100g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
