# Generated by Django 6.1 on 2026-08-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_ingredient_search_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='package_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ProductUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=30)),
                ('grams_per_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('source', models.CharField(max_length=200)),
                ('confidence', models.CharField(choices=[('verified', 'Verifiziert'), ('reference', 'Referenzwert'), ('estimated', 'Schätzwert')], default='reference', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='products.product')),
            ],
            options={
                'ordering': ['unit'],
                'constraints': [models.UniqueConstraint(fields=('product', 'unit'), name='unique_product_unit_conversion'), models.CheckConstraint(condition=models.Q(('grams_per_unit__gt', 0)), name='positive_product_unit_conversion')],
            },
        ),
    ]
