# Generated by Django 4.2.29 on 2026-03-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='shopping_list',
        ),
        migrations.AddField(
            model_name='savedlistitem',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
    ]
