# Generated by Django 6.1 on 2026-08-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_shoppinglistitem_shopping_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlistitem',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
