# Generated by Django 6.1 on 2026-08-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_category_recipe_description_recipe_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilokalorien pro Portion', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kohlenhydrate in Gramm pro Portion', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Geschätzter Gesamtpreis des Rezepts', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fett in Gramm pro Portion', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ballaststoffe in Gramm pro Portion', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Protein in Gramm pro Portion', max_digits=8, null=True),
        ),
    ]
