# Generated by Django 6.1 on 2026-08-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_default_unit_alter_product_name'),
        ('recipes', '0004_recipe_calories_recipe_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
